/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GerenteDashboardRouteImport } from './routes/gerente.dashboard'
import { Route as AtendenteMaquinasRouteImport } from './routes/atendente.maquinas'
import { Route as AtendenteFilaRouteImport } from './routes/atendente.fila'
import { Route as AtendenteDashboardRouteImport } from './routes/atendente.dashboard'
import { Route as AtendenteClientesRouteImport } from './routes/atendente.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteDashboardRoute = GerenteDashboardRouteImport.update({
  id: '/gerente/dashboard',
  path: '/gerente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteMaquinasRoute = AtendenteMaquinasRouteImport.update({
  id: '/atendente/maquinas',
  path: '/atendente/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteFilaRoute = AtendenteFilaRouteImport.update({
  id: '/atendente/fila',
  path: '/atendente/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteDashboardRoute = AtendenteDashboardRouteImport.update({
  id: '/atendente/dashboard',
  path: '/atendente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteClientesRoute = AtendenteClientesRouteImport.update({
  id: '/atendente/clientes',
  path: '/atendente/clientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/clientes': typeof AtendenteClientesRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/atendente/fila': typeof AtendenteFilaRoute
  '/atendente/maquinas': typeof AtendenteMaquinasRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/clientes': typeof AtendenteClientesRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/atendente/fila': typeof AtendenteFilaRoute
  '/atendente/maquinas': typeof AtendenteMaquinasRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/clientes': typeof AtendenteClientesRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/atendente/fila': typeof AtendenteFilaRoute
  '/atendente/maquinas': typeof AtendenteMaquinasRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atendente/clientes'
    | '/atendente/dashboard'
    | '/atendente/fila'
    | '/atendente/maquinas'
    | '/gerente/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atendente/clientes'
    | '/atendente/dashboard'
    | '/atendente/fila'
    | '/atendente/maquinas'
    | '/gerente/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/atendente/clientes'
    | '/atendente/dashboard'
    | '/atendente/fila'
    | '/atendente/maquinas'
    | '/gerente/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AtendenteClientesRoute: typeof AtendenteClientesRoute
  AtendenteDashboardRoute: typeof AtendenteDashboardRoute
  AtendenteFilaRoute: typeof AtendenteFilaRoute
  AtendenteMaquinasRoute: typeof AtendenteMaquinasRoute
  GerenteDashboardRoute: typeof GerenteDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/dashboard': {
      id: '/gerente/dashboard'
      path: '/gerente/dashboard'
      fullPath: '/gerente/dashboard'
      preLoaderRoute: typeof GerenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/maquinas': {
      id: '/atendente/maquinas'
      path: '/atendente/maquinas'
      fullPath: '/atendente/maquinas'
      preLoaderRoute: typeof AtendenteMaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/fila': {
      id: '/atendente/fila'
      path: '/atendente/fila'
      fullPath: '/atendente/fila'
      preLoaderRoute: typeof AtendenteFilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/dashboard': {
      id: '/atendente/dashboard'
      path: '/atendente/dashboard'
      fullPath: '/atendente/dashboard'
      preLoaderRoute: typeof AtendenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/clientes': {
      id: '/atendente/clientes'
      path: '/atendente/clientes'
      fullPath: '/atendente/clientes'
      preLoaderRoute: typeof AtendenteClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AtendenteClientesRoute: AtendenteClientesRoute,
  AtendenteDashboardRoute: AtendenteDashboardRoute,
  AtendenteFilaRoute: AtendenteFilaRoute,
  AtendenteMaquinasRoute: AtendenteMaquinasRoute,
  GerenteDashboardRoute: GerenteDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
