/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GerenteSessoesRouteImport } from './routes/gerente.sessoes'
import { Route as GerenteRelatoriosRouteImport } from './routes/gerente.relatorios'
import { Route as GerentePromocoesRouteImport } from './routes/gerente.promocoes'
import { Route as GerenteMaquinasRouteImport } from './routes/gerente.maquinas'
import { Route as GerenteHistoricoRouteImport } from './routes/gerente.historico'
import { Route as GerenteFuncionariosRouteImport } from './routes/gerente.funcionarios'
import { Route as GerenteFinancasRouteImport } from './routes/gerente.financas'
import { Route as GerenteDashboardRouteImport } from './routes/gerente.dashboard'
import { Route as GerenteClientesRouteImport } from './routes/gerente.clientes'
import { Route as AtendenteMaquinasRouteImport } from './routes/atendente.maquinas'
import { Route as AtendenteFilaRouteImport } from './routes/atendente.fila'
import { Route as AtendenteDashboardRouteImport } from './routes/atendente.dashboard'
import { Route as AtendenteClientesRouteImport } from './routes/atendente.clientes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteSessoesRoute = GerenteSessoesRouteImport.update({
  id: '/gerente/sessoes',
  path: '/gerente/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteRelatoriosRoute = GerenteRelatoriosRouteImport.update({
  id: '/gerente/relatorios',
  path: '/gerente/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const GerentePromocoesRoute = GerentePromocoesRouteImport.update({
  id: '/gerente/promocoes',
  path: '/gerente/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteMaquinasRoute = GerenteMaquinasRouteImport.update({
  id: '/gerente/maquinas',
  path: '/gerente/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteHistoricoRoute = GerenteHistoricoRouteImport.update({
  id: '/gerente/historico',
  path: '/gerente/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteFuncionariosRoute = GerenteFuncionariosRouteImport.update({
  id: '/gerente/funcionarios',
  path: '/gerente/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteFinancasRoute = GerenteFinancasRouteImport.update({
  id: '/gerente/financas',
  path: '/gerente/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteDashboardRoute = GerenteDashboardRouteImport.update({
  id: '/gerente/dashboard',
  path: '/gerente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteClientesRoute = GerenteClientesRouteImport.update({
  id: '/gerente/clientes',
  path: '/gerente/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteMaquinasRoute = AtendenteMaquinasRouteImport.update({
  id: '/atendente/maquinas',
  path: '/atendente/maquinas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteFilaRoute = AtendenteFilaRouteImport.update({
  id: '/atendente/fila',
  path: '/atendente/fila',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteDashboardRoute = AtendenteDashboardRouteImport.update({
  id: '/atendente/dashboard',
  path: '/atendente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteClientesRoute = AtendenteClientesRouteImport.update({
  id: '/atendente/clientes',
  path: '/atendente/clientes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/clientes': typeof AtendenteClientesRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/atendente/fila': typeof AtendenteFilaRoute
  '/atendente/maquinas': typeof AtendenteMaquinasRoute
  '/gerente/clientes': typeof GerenteClientesRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
  '/gerente/financas': typeof GerenteFinancasRoute
  '/gerente/funcionarios': typeof GerenteFuncionariosRoute
  '/gerente/historico': typeof GerenteHistoricoRoute
  '/gerente/maquinas': typeof GerenteMaquinasRoute
  '/gerente/promocoes': typeof GerentePromocoesRoute
  '/gerente/relatorios': typeof GerenteRelatoriosRoute
  '/gerente/sessoes': typeof GerenteSessoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/clientes': typeof AtendenteClientesRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/atendente/fila': typeof AtendenteFilaRoute
  '/atendente/maquinas': typeof AtendenteMaquinasRoute
  '/gerente/clientes': typeof GerenteClientesRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
  '/gerente/financas': typeof GerenteFinancasRoute
  '/gerente/funcionarios': typeof GerenteFuncionariosRoute
  '/gerente/historico': typeof GerenteHistoricoRoute
  '/gerente/maquinas': typeof GerenteMaquinasRoute
  '/gerente/promocoes': typeof GerentePromocoesRoute
  '/gerente/relatorios': typeof GerenteRelatoriosRoute
  '/gerente/sessoes': typeof GerenteSessoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/clientes': typeof AtendenteClientesRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/atendente/fila': typeof AtendenteFilaRoute
  '/atendente/maquinas': typeof AtendenteMaquinasRoute
  '/gerente/clientes': typeof GerenteClientesRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
  '/gerente/financas': typeof GerenteFinancasRoute
  '/gerente/funcionarios': typeof GerenteFuncionariosRoute
  '/gerente/historico': typeof GerenteHistoricoRoute
  '/gerente/maquinas': typeof GerenteMaquinasRoute
  '/gerente/promocoes': typeof GerentePromocoesRoute
  '/gerente/relatorios': typeof GerenteRelatoriosRoute
  '/gerente/sessoes': typeof GerenteSessoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/atendente/clientes'
    | '/atendente/dashboard'
    | '/atendente/fila'
    | '/atendente/maquinas'
    | '/gerente/clientes'
    | '/gerente/dashboard'
    | '/gerente/financas'
    | '/gerente/funcionarios'
    | '/gerente/historico'
    | '/gerente/maquinas'
    | '/gerente/promocoes'
    | '/gerente/relatorios'
    | '/gerente/sessoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/atendente/clientes'
    | '/atendente/dashboard'
    | '/atendente/fila'
    | '/atendente/maquinas'
    | '/gerente/clientes'
    | '/gerente/dashboard'
    | '/gerente/financas'
    | '/gerente/funcionarios'
    | '/gerente/historico'
    | '/gerente/maquinas'
    | '/gerente/promocoes'
    | '/gerente/relatorios'
    | '/gerente/sessoes'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/atendente/clientes'
    | '/atendente/dashboard'
    | '/atendente/fila'
    | '/atendente/maquinas'
    | '/gerente/clientes'
    | '/gerente/dashboard'
    | '/gerente/financas'
    | '/gerente/funcionarios'
    | '/gerente/historico'
    | '/gerente/maquinas'
    | '/gerente/promocoes'
    | '/gerente/relatorios'
    | '/gerente/sessoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AtendenteClientesRoute: typeof AtendenteClientesRoute
  AtendenteDashboardRoute: typeof AtendenteDashboardRoute
  AtendenteFilaRoute: typeof AtendenteFilaRoute
  AtendenteMaquinasRoute: typeof AtendenteMaquinasRoute
  GerenteClientesRoute: typeof GerenteClientesRoute
  GerenteDashboardRoute: typeof GerenteDashboardRoute
  GerenteFinancasRoute: typeof GerenteFinancasRoute
  GerenteFuncionariosRoute: typeof GerenteFuncionariosRoute
  GerenteHistoricoRoute: typeof GerenteHistoricoRoute
  GerenteMaquinasRoute: typeof GerenteMaquinasRoute
  GerentePromocoesRoute: typeof GerentePromocoesRoute
  GerenteRelatoriosRoute: typeof GerenteRelatoriosRoute
  GerenteSessoesRoute: typeof GerenteSessoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/sessoes': {
      id: '/gerente/sessoes'
      path: '/gerente/sessoes'
      fullPath: '/gerente/sessoes'
      preLoaderRoute: typeof GerenteSessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/relatorios': {
      id: '/gerente/relatorios'
      path: '/gerente/relatorios'
      fullPath: '/gerente/relatorios'
      preLoaderRoute: typeof GerenteRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/promocoes': {
      id: '/gerente/promocoes'
      path: '/gerente/promocoes'
      fullPath: '/gerente/promocoes'
      preLoaderRoute: typeof GerentePromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/maquinas': {
      id: '/gerente/maquinas'
      path: '/gerente/maquinas'
      fullPath: '/gerente/maquinas'
      preLoaderRoute: typeof GerenteMaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/historico': {
      id: '/gerente/historico'
      path: '/gerente/historico'
      fullPath: '/gerente/historico'
      preLoaderRoute: typeof GerenteHistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/funcionarios': {
      id: '/gerente/funcionarios'
      path: '/gerente/funcionarios'
      fullPath: '/gerente/funcionarios'
      preLoaderRoute: typeof GerenteFuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/financas': {
      id: '/gerente/financas'
      path: '/gerente/financas'
      fullPath: '/gerente/financas'
      preLoaderRoute: typeof GerenteFinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/dashboard': {
      id: '/gerente/dashboard'
      path: '/gerente/dashboard'
      fullPath: '/gerente/dashboard'
      preLoaderRoute: typeof GerenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/clientes': {
      id: '/gerente/clientes'
      path: '/gerente/clientes'
      fullPath: '/gerente/clientes'
      preLoaderRoute: typeof GerenteClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/maquinas': {
      id: '/atendente/maquinas'
      path: '/atendente/maquinas'
      fullPath: '/atendente/maquinas'
      preLoaderRoute: typeof AtendenteMaquinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/fila': {
      id: '/atendente/fila'
      path: '/atendente/fila'
      fullPath: '/atendente/fila'
      preLoaderRoute: typeof AtendenteFilaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/dashboard': {
      id: '/atendente/dashboard'
      path: '/atendente/dashboard'
      fullPath: '/atendente/dashboard'
      preLoaderRoute: typeof AtendenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/clientes': {
      id: '/atendente/clientes'
      path: '/atendente/clientes'
      fullPath: '/atendente/clientes'
      preLoaderRoute: typeof AtendenteClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AtendenteClientesRoute: AtendenteClientesRoute,
  AtendenteDashboardRoute: AtendenteDashboardRoute,
  AtendenteFilaRoute: AtendenteFilaRoute,
  AtendenteMaquinasRoute: AtendenteMaquinasRoute,
  GerenteClientesRoute: GerenteClientesRoute,
  GerenteDashboardRoute: GerenteDashboardRoute,
  GerenteFinancasRoute: GerenteFinancasRoute,
  GerenteFuncionariosRoute: GerenteFuncionariosRoute,
  GerenteHistoricoRoute: GerenteHistoricoRoute,
  GerenteMaquinasRoute: GerenteMaquinasRoute,
  GerentePromocoesRoute: GerentePromocoesRoute,
  GerenteRelatoriosRoute: GerenteRelatoriosRoute,
  GerenteSessoesRoute: GerenteSessoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
