/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GerenteDashboardRouteImport } from './routes/gerente.dashboard'
import { Route as AtendenteDashboardRouteImport } from './routes/atendente.dashboard'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenteDashboardRoute = GerenteDashboardRouteImport.update({
  id: '/gerente/dashboard',
  path: '/gerente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendenteDashboardRoute = AtendenteDashboardRouteImport.update({
  id: '/atendente/dashboard',
  path: '/atendente/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/atendente/dashboard': typeof AtendenteDashboardRoute
  '/gerente/dashboard': typeof GerenteDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/atendente/dashboard' | '/gerente/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/atendente/dashboard' | '/gerente/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/atendente/dashboard'
    | '/gerente/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AtendenteDashboardRoute: typeof AtendenteDashboardRoute
  GerenteDashboardRoute: typeof GerenteDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerente/dashboard': {
      id: '/gerente/dashboard'
      path: '/gerente/dashboard'
      fullPath: '/gerente/dashboard'
      preLoaderRoute: typeof GerenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendente/dashboard': {
      id: '/atendente/dashboard'
      path: '/atendente/dashboard'
      fullPath: '/atendente/dashboard'
      preLoaderRoute: typeof AtendenteDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AtendenteDashboardRoute: AtendenteDashboardRoute,
  GerenteDashboardRoute: GerenteDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
